services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - target_postgres_data:/var/lib/postgresql

  receiver:
    build:
      context: .
      dockerfile: receiver.DOCKERFILE
    restart: always
    depends_on:
      - postgres
    environment:
      TARGET_DB_HOST: postgres
      TARGET_DB_PORT: ${DB_PORT}
      TARGET_DB_NAME: ${DB_NAME}
      TARGET_DB_USER: ${DB_USER}
      TARGET_DB_PASSWORD: ${DB_PASSWORD}
      API_KEY: ${API_KEY}

volumes:
  target_postgres_data: