services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - target_postgres_data:/var/lib/postgresql

  receiver:
    build:
      context: .
      dockerfile: receiver.DOCKERFILE
    restart: always
    depends_on:
      - postgres
    environment:
      SOURCE_URL: http://192.168.122.18:5000/replicate
      TARGET_DB_HOST: postgres
      TARGET_DB_PORT: "5432"
      TARGET_DB_NAME: mydatabase
      TARGET_DB_USER: myuser
      TARGET_DB_PASSWORD: mypassword

volumes:
  target_postgres_data: