server {
	listen 80;
	server_name localhost 127.0.0.1;

	return 301 https://localhost$request_uri;
}

server {
	listen 443 ssl;
	server_name localhost 127.0.0.1;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log warn;

	ssl_certificate /etc/nginx/certs/nginx.crt;
	ssl_certificate_key /etc/nginx/certs/nginx.key;

	location / {
		proxy_pass http://sender:5000;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
